services:
  api-gateway:
    build:
      dockerfile: ./src/Dockerfile
    ports:
      - 8080:8080
    networks:
      - client-be
      - auth
      - farmer-be
      - image


networks:
  client-be:
    name: g-client-be
  auth:
    name: g-auth
  farmer-be:
    name: g-farmer-be
  image:
    name: g-images
