services:
  api-gateway:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - client-be
      - auth


networks:
  client-be:
    name: client-be
  auth:
    name: auth
